on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: opstestreg.azurecr.io
        username: ${{ secrets.acr_opstestreg_username }}
        password: ${{ secrets.acr_opstestreg_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t opstestreg.azurecr.io/testcluster0:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push opstestreg.azurecr.io/testcluster0:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_testcluster0_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep test-cluster-0971a | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace test-cluster-0971a`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: test-cluster-0971a
        container-registry-url: opstestreg.azurecr.io
        container-registry-username: ${{ secrets.acr_opstestreg_username }}
        container-registry-password: ${{ secrets.acr_opstestreg_password }}
        secret-name: testcluster0dockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: test-cluster-0971a
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          opstestreg.azurecr.io/testcluster0:${{ github.sha }}
        imagepullsecrets: |
          testcluster0dockerauth
